### PR TITLE
fix: ensure we always have an ID

### LINKED ISSUE #66: Provider could not decode JSON response
Today I tested the provider and found that it seams there is an issue with decoding the response from PagerDuty. Applying the following team
```
apiVersion: team.pagerduty.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
  name: test-team
spec:
  deletionPolicy: Delete
  forProvider:
    description: Product and Engineering
    name: Product Development
```
I get the following error:
```
cannot run refresh: refresh failed: Error reading PagerDuty team : Could not decode JSON response: json: cannot unmarshal array into Go value of type pagerduty.Team
```
I got the same error when trying to create a business service. Can someone have a look a this issue?

### PR DESCRIPTION
**Pull request by fernandezcuesta**
### Description of your changes

`id` field in tfstate must be either filled in or omitted. This PR attempts to fix it by setting an intermediate value (PENDING) not to fall into the raised bug.

Fixes #66 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Locally with valid credentials.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by fernandezcuesta** [comment]
Not sure if it is possible to omit the id from the tfstate, but when we get the following we hit the bug as per #66:

```json
{
  "version": 4,
  "terraform_version": "1.5.5",
  "serial": 1,
  "lineage": "8a917ef2-2690-4360-9d29-0bf2a4dfe8b7",
  "outputs": null,
  "resources": [
    {
      "mode": "managed",
      "type": "pagerduty_team",
      "name": "test-team",
      "provider": "provider[\"registry.terraform.io/PagerDuty/pagerduty\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "Test team",
            "id": "",
            "name": "Test Team"
          }
        }
      ]
    }
  ]
}
```

**Comment by fernandezcuesta** [comment]
Looks to me like an error in the upstream terraform provider, which doesn't like having an empty id. Didn't find the way to instruct upjet not to set it in the tfstate

**Comment by fnicolelli-ls** [comment]
Hello team,
i've tested this locally and it is working, i can deploy pagerduty Teams without any issues.

**Comment by mergenci** [comment]
Having empty IDs is common in Terraform Plugin Framework resources, which [PagerDuty Team is](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/master/pagerdutyplugin/resource_pagerduty_team.go#L11-L15). We return a stub value as external name for such resources (see [this example](https://github.com/crossplane-contrib/provider-upjet-aws/blob/14b3dceded47996722668d6cf67c9835a27b13c3/config/externalname.go#L2958-L2968)). I cannot talk about the soundness of the implementation in this PR, but the approach is valid.

**Comment by fernandezcuesta** [comment]
Closing in favor of #71 where only the fixes related to #66 are included.

**Pull request closed without merging**
